### ISSUE TITLE
[Feature request] Allow specifying a border

### ISSUE THREAD

**Issue by akinsho** [b0o/incline.nvim#13]
Hi,

Not sure if there's a specific implementation reason to avoid this, but I'm essentially trying to draw a bottom border on the window line to demarcate it a bit better from the buffer content rather than changing the colour of the window, which over time I've found too distracting on a small laptop screen. I tried overwriting the window config in a filetype autocommand (which didn't work), but I personally dislike that way of setting options anyway and think an explicit option would be much nicer.

<img width="1507" alt="Screen Shot 2022-05-07 at 08 01 56" src="https://user-images.githubusercontent.com/22454918/167240969-b56ec541-3245-494d-b784-dc0e6b8f6055.png">

**Comment by b0o** [comment]
I did look into setting borders, but I personally don't think they work very well for this use case. The issue is that it causes incline to take up 2-3 vertical rows which is a lot of space to lose.

Full borders:

![2022-05-06_23-12-57_region](https://user-images.githubusercontent.com/21299126/167241280-6bbf52ef-0ca1-43b5-be22-b6efe434a5e8.png)

Bottom border:

![2022-05-06_23-15-37_region](https://user-images.githubusercontent.com/21299126/167241412-e5340434-f6f6-4f22-a4bb-9facc08e040d.png)

If you still think this would be useful, I'm not opposed to adding it. It will require re-working the positioning calculations a bit.

**Comment by milanglacier** [comment]
I think the easiest way is to expose a `autocmd User InclineAdjustWinlineConfig`, and call `doautocmd xxx` in the code.
and the user can reset the config whatever they want by implementing the autocmd itself.
Adjusting the logic of the window position calculation is something tedious, it just requires live view interaction with the nvim window to figure out the correct logic.

**Comment by akinsho** [comment]
@b0o I personally would only use the bottom border so would only be loosing a single line, I think the extra demarcation would be nice visually if it doesn't come at too much of a cost on your side. It's definitely not the end of the world, but I do like the bottom border examples you posted, although in my case this will be across the entire window.

Re. the above comment on user autocommands and manually messing with nvim window  configs I think that's quite a messy and potentially error-prone way to expose this sort of functionality and is best done via just a setting in the plugins options

**Comment by b0o** [comment]
Sounds good to me, I will add support for borders in the near future.

And a bottom border with `width = "fill"` does look pretty neat!

![2022-05-06_23-49-10_region](https://user-images.githubusercontent.com/21299126/167242584-fc5f4e84-6150-41f1-9795-1bde6098b686.png)

**Comment by b0o** [comment]
And yes, cursors getting hidden is an issue. I plan to add a `hide.cursorline` configuration option for users who keep Incline enabled for the focused win but don't want it showing if their cursor is on the same line.

**Comment by b0o** [comment]
I've decided not to support this feature.
